name: Code Coverage
on: 
  workflow_dispatch:
jobs:
  code-coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - uses: eWaterCycle/setup-singularity@v6
        with:
          singularity-version: 3.7.1

      - name: Generate coverage report
        run: |
          pip install .
          wget --quiet -O image.sif https://osf.io/792up/download
          pytest tests/unit_tests.py --cov=mappertrac/subscripts/ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
