name: Code Coverage
on: 
  workflow_dispatch:
jobs:
  code-coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Generate coverage report
        run: |
          pip install .
          wget -O image.sif https://osf.io/792up/download
          pytest --cov=mappertrac/ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true